export const TOOLS = [
  { id: "merge-pdf", name: "Merge PDFs", icon: "file-plus-outline" as const, description: "Combine multiple PDFs", category: "pdf" },
  { id: "split-pdf", name: "Split PDF", icon: "file-document-multiple-outline" as const, description: "Split PDF into pages", category: "pdf" },
  { id: "compress-pdf", name: "Compress PDF", icon: "arrow-collapse" as const, description: "Reduce PDF file size", category: "pdf" },
  {
    id: "organize-pdf",
    name: "Organize PDF",
    icon: "file-move-outline" as const,
    description: "Reorder, rotate, or delete pages",
    category: "pdf",
  },
  {
    id: "add-page-numbers",
    name: "Add Page Numbers",
    icon: "format-list-numbered" as const,
    description: "Insert page numbers into a PDF",
    category: "pdf",
  },
  { id: "remove-bg", name: "Remove Background", icon: "image-edit-outline" as const, description: "Remove image background", category: "image" },
  {
    id: "extract-pdf-pages",
    name: "Extract PDF Pages",
    icon: "file-export-outline" as const,
    description: "Create a new PDF from selected pages",
    category: "pdf",
  },
  {
    id: "remove-pdf-pages",
    name: "Remove PDF Pages",
    icon: "file-remove-outline" as const,
    description: "Permanently delete specific pages",
    category: "pdf",
  },
  { id: "pdf-to-word", name: "PDF to Word", icon: "file-word-outline" as const, description: "Convert PDF to Word", category: "pdf" },
  { id: "word-to-pdf", name: "Word to PDF", icon: "file-word-outline" as const, description: "Convert Word to PDF", category: "docx" },
  { id: "excel-to-pdf", name: "Excel to PDF", icon: "file-excel-outline" as const, description: "Convert Excel to PDF", category: "excel" },
  { id: "pdf-to-excel", name: "PDF to Excel", icon: "file-excel-outline" as const, description: "Convert PDF to Excel", category: "pdf" },
  { id: "image-to-pdf", name: "Image to PDF", icon: "file-image-outline" as const, description: "Convert images to PDF", category: "image" },
  { id: "pdf-to-image", name: "PDF to Image", icon: "file-image-outline" as const, description: "Convert PDF to Image", category: "pdf" },
  
];